language: java
env:
  - MYSQL_VERSION=5.5
  - MYSQL_VERSION=5.6
install: true
script:
  - make test
  - "cat test.log | awk '/begin-test/ { PRINT=1 } /end-test/ { PRINT=0 } { if (PRINT == 1)  print $0  } '"
